"""Reverse conversion: Terraria armor textures -> ArmorHelper template.

Because ``generate`` is a pure pixel copy + nearest neighbour upscale, it can be
undone.  Everything the generator writes into a texture comes from exactly one
place in the template, so the template can be rebuilt by walking the same tables
backwards.  The mapping is verified by ``tests/test_reverse.py`` (round trip on
the bundled template) and by the fact that *every* vanilla armor texture is an
exact 2x nearest neighbour upscale of 1x art.

Limitations
-----------
* Pixels with ``alpha <= 1`` are invisible to the generator and therefore cannot
  be recovered; the rebuilt template leaves them transparent.
* The body frames 3, 4 and 5 have no back arm in the original tool, so nothing
  is recovered for them (there is nothing to recover).
* The arms used while swinging an item (columns 7 and 8) are thrown away; they
  are regenerated by the tool.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image

from . import layout as L
from .generate import _back_arm_layer, _front_arm_layer
from .imaging import new_canvas, paste_region

__all__ = ["ReverseResult", "reverse_template", "reverse_from_images", "load_texture"]


@dataclass
class ReverseResult:
    template: Image.Image
    head_id: int | None = None
    body_id: int | None = None
    legs_id: int | None = None
    set_name: str | None = None
    warnings: list[str] = field(default_factory=list)

    @property
    def ids(self) -> str:
        def show(value: int | None) -> str:
            return str(value) if value is not None else "-"

        return f"head={show(self.head_id)} body={show(self.body_id)} legs={show(self.legs_id)}"


def _halve(image: Image.Image) -> Image.Image:
    """Undo the generator's 2x nearest neighbour upscale."""
    if image.width % 2 or image.height % 2:
        raise ValueError(f"{image.width}x{image.height} is not a 2x texture")
    return image.resize((image.width // 2, image.height // 2), Image.NEAREST)


def _cell(sheet: Image.Image, col: int, row: int) -> Image.Image:
    x, y = col * L.FRAME_W, row * L.FRAME_H
    return sheet.crop((x, y, x + L.FRAME_W, y + L.FRAME_H))


def _rect(sheet: Image.Image, x: int, y: int, width: int, height: int) -> Image.Image:
    """``crop`` with ``(x, y, width, height)`` instead of PIL's corner pair."""
    return sheet.crop((x, y, x + width, y + height))


def _copy_back(template: Image.Image, region: Image.Image, dest: tuple[int, int]) -> None:
    """Write ``region`` into the template at ``dest`` (transparent pixels skipped)."""
    paste_region(template, region, (0, 0, region.width, region.height), dest)


# --------------------------------------------------------------------------- #


def _reverse_head(template: Image.Image, head: Image.Image) -> None:
    sheet = _halve(head)  # 20x560
    # Body frame 0 has no bob, so it holds the untouched head art.
    _copy_back(template, _rect(sheet, 0, 0, L.FRAME_W, L.FRAME_H), L.HEAD_SRC[:2])


#: ``(body frame, x of the front foot, x of the back foot)``.  The generator
#: swaps the two feet around on body frame 19, which is what makes it possible
#: to recover both sprites.
_FOOT_PLACEMENTS = ((0, 5, 7), (11, 5, 7), (19, 7, 5))

#: Source pixels the generator deliberately skips on row 2 of both feet.
_FOOT_MASKED_ROW = 2
_FOOT_MASKED_COLUMNS = (1, 7)


def _front_covers(front_art: Image.Image, column: int, row: int) -> bool:
    """Is the front foot actually drawn over ``(column, row)`` of the back foot?"""
    if not 0 <= column < 9:
        return False
    if row == _FOOT_MASKED_ROW and column in _FOOT_MASKED_COLUMNS:
        return False  # the generator never copies this pixel
    return front_art.getpixel((column, row))[3] > 1


def _reverse_legs(template: Image.Image, legs: Image.Image) -> None:
    sheet = _halve(legs)  # 20x560

    # The front foot is easy: body frame 6 carries an extra, complete copy at
    # x=6, made without the masking the normal copies use.
    front_art = _rect(sheet, 6, 6 * L.FRAME_H + 19, 9, 9)
    _copy_back(template, front_art, L.LEG_FOOT_FRONT[:2])

    # The back foot is drawn underneath the front one, which hides most of it.
    # Body frames 0 and 19 place the two feet on opposite sides, so combining
    # them recovers every pixel that is visible in at least one frame.
    back_art = new_canvas(9, 9)
    for frame, front_x, back_x in _FOOT_PLACEMENTS:
        region = _rect(sheet, back_x, frame * L.FRAME_H + 19, 9, 9)
        for row in range(9):
            for column in range(9):
                if back_art.getpixel((column, row))[3] > 1:
                    continue
                if _front_covers(front_art, back_x + column - front_x, row):
                    continue
                pixel = region.getpixel((column, row))
                if pixel[3] > 1:
                    back_art.putpixel((column, row), pixel)
    _copy_back(template, back_art, L.LEG_FOOT_BACK[:2])

    for index, targets in enumerate(L.LEG_MAPPING):
        column_x = L.LEG_COLUMN_RIGHT[0] if index >= 5 else L.LEG_COLUMN_LEFT[0]
        source_y = 19 + (index % 5) * 10
        frame = targets[0]
        region = _rect(sheet, 3, 19 + frame * L.FRAME_H, 16, 9)
        _copy_back(template, region, (column_x, source_y))


def _merge_torso(torso: Image.Image, back_shoulder: Image.Image, front_shoulder: Image.Image):
    """Fold the two shoulder sprites into the torso, in the game's draw order.

    The template has no shoulder regions, so the shoulder cells are merged into
    the torso: the back shoulder first (the torso then covers it), then the
    torso, then the front shoulder on top.
    """
    merged = new_canvas(L.FRAME_W, L.FRAME_H)
    rect = (0, 0, L.FRAME_W, L.FRAME_H)
    paste_region(merged, back_shoulder, rect, (0, 0))
    paste_region(merged, torso, rect, (0, 0))
    paste_region(merged, front_shoulder, rect, (0, 0))
    return merged


def _reverse_body(template: Image.Image, body: Image.Image, warnings: list[str]) -> None:
    if body.height < L.FRAME_H * 2 * L.BODY_COMPOSITE_ROWS:
        raise ValueError("body texture is too small for the 9x4 composite layout")
    sheet = _halve(body)

    # --- torsos, with the shoulder layers folded in ----------------------
    for source, torso_cell, back_cell, front_cell in (
        (L.BODY_SRC, (0, 0), L.BACK_SHOULDER_CELL, L.FRONT_SHOULDER_CELL),
        (L.BODY_JUMP_SRC, (1, 0), L.BACK_SHOULDER_CELL, L.FRONT_SHOULDER_CELL),
        (L.FEMALE_SRC, (0, 2), (1, 3), (0, 3)),
        (L.FEMALE_JUMP_SRC, (1, 2), (1, 3), (0, 3)),
    ):
        merged = _merge_torso(
            _cell(sheet, *torso_cell), _cell(sheet, *back_cell), _cell(sheet, *front_cell)
        )
        _copy_back(template, merged, source[:2])

    # --- front arm poses for body frames 0..4 ---------------------------
    for frame in range(5):
        layer = _front_arm_layer(frame)
        if layer is None:
            continue
        rect, (offset_x, offset_y), _ = layer
        region = _rect(_cell(sheet, *L.FRONT_ARM_CELL[frame]), offset_x, offset_y, rect[2], rect[3])
        _copy_back(template, region, (rect[0], rect[1]))

    # --- the "walk" front arm -------------------------------------------
    # Cells (3,1).. (6,1) all come from the same template rectangle with
    # different horizontal offsets; the frame 6 cell has offset 0 and is the
    # only one that covers it completely.
    layer = _front_arm_layer(6)
    if layer is not None:
        rect, (offset_x, offset_y), _ = layer
        region = _rect(_cell(sheet, *L.FRONT_ARM_CELL[6]), offset_x, offset_y, rect[2], rect[3])
        _copy_back(template, region, (rect[0], rect[1]))

    # --- the back arm ---------------------------------------------------
    layer = _back_arm_layer(0)
    if layer is not None:
        blits, _stray = layer
        rect, (offset_x, offset_y) = blits[0]
        region = _rect(_cell(sheet, *L.BACK_ARM_CELL[0]), offset_x, offset_y, rect[2], rect[3])
        _copy_back(template, region, (rect[0], rect[1]))

    # --- the stray single pixel of body frames 15 and 16 ----------------
    for frame in (15, 16):
        layer = _back_arm_layer(frame)
        if not layer:
            continue
        _blits, stray = layer
        if stray is None:
            continue
        (rect, (offset_x, offset_y)) = stray
        region = _rect(_cell(sheet, *L.BACK_ARM_CELL[frame]), offset_x, offset_y, rect[2], rect[3])
        _copy_back(template, region, (rect[0], rect[1]))

    if sheet.height >= L.FRAME_H * (L.BODY_COMPOSITE_ROWS + L.BODY_GLOW_ROWS):
        warnings.append("the texture has a glow mask; it is only used in game and is not reversed")


# --------------------------------------------------------------------------- #


def reverse_template(
    *,
    head: Image.Image | None = None,
    body: Image.Image | None = None,
    legs: Image.Image | None = None,
    head_id: int | None = None,
    body_id: int | None = None,
    legs_id: int | None = None,
    set_name: str | None = None,
) -> ReverseResult:
    """Rebuild a 128x80 template from up to three Terraria armor textures."""
    template = new_canvas(*L.TEMPLATE_SIZE)
    warnings: list[str] = []

    if body is not None:
        _reverse_body(template, body, warnings)
    else:
        warnings.append("no body texture: the torso and the arms cannot be recovered")
    if head is not None:
        _reverse_head(template, head)
    else:
        warnings.append("no head texture: the head region is left empty")
    if legs is not None:
        _reverse_legs(template, legs)
    else:
        warnings.append("no legs texture: the legs region is left empty")

    return ReverseResult(
        template=template,
        head_id=head_id,
        body_id=body_id,
        legs_id=legs_id,
        set_name=set_name,
        warnings=warnings,
    )


# --------------------------------------------------------------------------- #
# Loading from a Terraria Content/Images folder
# --------------------------------------------------------------------------- #


def texture_paths(images_dir: str | Path, *, head: int | None, body: int | None, legs: int | None):
    """Locate the three textures, tolerating both known body folder layouts."""
    root = Path(images_dir)

    def find(*candidates: str) -> Path | None:
        for candidate in candidates:
            path = root / candidate
            if path.exists():
                return path
        return None

    return {
        "head": find(f"Armor_Head_{head}.png") if head is not None else None,
        "body": find(f"Armor/Armor_{body}.png", f"Armor_{body}.png")
        if body is not None
        else None,
        "legs": find(f"Armor_Legs_{legs}.png") if legs is not None else None,
    }


def load_texture(path: str | Path | None) -> Image.Image | None:
    if path is None:
        return None
    with Image.open(path) as image:
        return image.convert("RGBA")


def reverse_from_images(
    images_dir: str | Path,
    *,
    body: int,
    head: int | None = None,
    legs: int | None = None,
    set_name: str | None = None,
) -> ReverseResult:
    """Load the textures for the given armor ids and rebuild the template."""
    paths = texture_paths(images_dir, head=head, body=body, legs=legs)
    result = reverse_template(
        head=load_texture(paths["head"]),
        body=load_texture(paths["body"]),
        legs=load_texture(paths["legs"]),
        head_id=head,
        body_id=body,
        legs_id=legs,
        set_name=set_name,
    )
    for kind, path in paths.items():
        if path is None:
            label = {"head": head, "body": body, "legs": legs}[kind]
            if label is not None:
                result.warnings.append(f"Armor_{kind}_{label}.png not found in {images_dir}")
    return result
